language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29
install: ant deps
jobs:
  include:
    - stage: build
      script:
      - bash ./gradlew \
        build \
        jacocoTestReport
      after_success:
      - export CODECOV_TOKEN="d2c32f08-36bf-42d5-a9ff-20cb771f92a7"
      - bash <(curl -s https://codecov.io/bash)
