language: android
jdk: oraclejdk8
dist: trusty
os: linux
android:
    components:
        - tools
        - build-tools-29.0.3
        - android-29
jobs:
    include:
    - stage: build
      script:
      - |
        ./gradlew \
        build \
        jacocoTestReport
      after_success:
      - bash <(curl -s https://codecov.io/bash)
